kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx-replicaset
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      apps: nginx

  template:
    metadata:
      name: nginx-pod
      labels: 
        apps: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

        
